=== Backbase/backbase-openapi-tools/boat-maven-plugin/src/it/example/boat-export/raml-specs/raml-spec/src/main/resources/common-schemas/body/paymentcard-item.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "javaType":"com.backbase.buildingblocks.test.data.PaymentCard",
  "properties": {
    "id": {
      "type": "string"
    },
    "pan": {
      "type": "string",
      "description": "Must be sixteen digits, optionally in blocks of 4 separated by a dash",
      "maxLength": 19
    },
    "cvc": {
      "type": "string",
      "description": "Card Verification Code",
      "minLength": 3,
      "maxLength": 3
    },
    "startDate": {
      "type": "string",
      "description": "Must be in one of these four formats: MM/YY MMYY MMYYYY MM/YYYY",
      "pattern": "^(0[1-9]|1[0-2])\/?([0-9]{4}|[0-9]{2})$"
    },
    "expiryDate": {
      "type": "string",
      "description": "Must be in one of these four formats: MM/YY MMYY MMYYYY MM/YYYY",
      "pattern": "^(0[1-9]|1[0-2])\/?([0-9]{4}|[0-9]{2})$"
    },
    "nameOnCard": {
      "type": "string"
    },
    "creationDate" : { 
      "type":"string", 
      "format":"date-time"
    },
    "balance" : {
      "type": "object",
      "$ref": "../../lib/types/schemas/currency.json"
    },
    "apr": {
      "type": "number",
      "javaType": "java.math.BigDecimal"
    },
    "cardtype" : {
      "type" : "string",
      "default" : "CREDIT",
      "enum" : ["CREDIT", "DEBIT", "PREPAID"]
    }
  },
  "required": [
    "id",
    "pan",
    "cvc",
    "startDate",
    "expiryDate",
    "nameOnCard"
  ]
}

=== Backbase/backbase-openapi-tools/boat-maven-plugin/src/it/example/boat-export/raml-specs/raml-spec/src/main/resources/examples/body/paymentcard-item.json
{
  "id": "a5b0fe7d-c4dd-40a7-bd80-dfc7869327e1",
  "pan": "5434111122223333",
  "cvc": "123",
  "startDate": "0116",
  "expiryDate": "1219",
  "nameOnCard": "Mr Timmy Tester",
  "creationDate": "2011-05-30T12:13:14+03:00",
  "balance": {
    "amount": "1000",
    "currencyCode": "EUR"
  },
  "apr": 12.75
}

=== Backbase/backbase-openapi-tools/boat-maven-plugin/src/it/example/boat-export/raml-specs/raml-spec/src/main/resources/examples/body/paymentcards-get.json
[
  {
    "id": "a5b0fe7d-c4dd-40a7-bd80-dfc7869327e1",
    "pan": "5434111122223333",
    "cvc": "123",
    "startDate": "0116",
    "expiryDate": "1219",
    "nameOnCard": "Mr Timmy Tester",
    "creationDate": "2011-05-30T12:13:14+03:00",
    "balance": {
      "amount": "2001",
      "currencyCode": "EUR"
    },
    "apr": 12.75
  },
  {
    "id": "d593c212-70ad-41a6-a547-d5d9232414cb",
    "pan": "5434111122224444",
    "cvc": "101",
    "startDate": "0216",
    "expiryDate": "0120",
    "nameOnCard": "Mr Timmothy Tester",
    "creationDate": "2011-05-30T12:13:14+03:00",
    "balance": {
      "amount": "4.4399999999999995",
      "currencyCode": "GBP"
    },
    "apr": 12.75
  },
  {
    "id": "9635966b-28e9-4479-8121-bb7bc9beeb62",
    "pan": "5434121212121212",
    "cvc": "121",
    "startDate": "0115",
    "expiryDate": "1218",
    "nameOnCard": "Mr Timmy Tester",
    "creationDate": "2011-05-30T12:13:14+03:00",
    "balance": {
      "amount": "1981",
      "currencyCode": "EUR"
    },
    "apr": 12.75
  }
]
